version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: my_django_db
      POSTGRES_USER: my_django_user
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"

  web:
    build:
      context: .
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./.env
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             python manage.py createsuperuser --noinput || echo 'Superuser already exists' &&
             python manage.py runserver 0.0.0.0:8000"

volumes:
  postgres_data:
